import { database, ensureDatabase } from "../../../db/runtime";
import { getViewer } from "../../../db/viewer";
import { env } from "cloudflare:workers";

export const providerIds = ["quickbooks", "gusto", "googleCalendar", "slack"] as const;
export type ProviderId = typeof providerIds[number];
type TokenSet = { accessToken: string; refreshToken?: string; expiresAt?: number };
type StoredConnection = { provider: ProviderId; encryptedTokens: string; accountId: string; accountName: string; connectedAt: number };
const providerNames: Record<ProviderId, string> = { quickbooks: "QuickBooks Online", gusto: "Gusto", googleCalendar: "Google Calendar", slack: "Slack" };

export function asProvider(value: string): ProviderId | null { return providerIds.includes(value as ProviderId) ? value as ProviderId : null; }
function envNames(provider: ProviderId) { if (provider === "quickbooks") return ["QUICKBOOKS_CLIENT_ID", "QUICKBOOKS_CLIENT_SECRET"] as const; if (provider === "googleCalendar") return ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"] as const; if (provider === "slack") return ["SLACK_CLIENT_ID", "SLACK_CLIENT_SECRET"] as const; return ["GUSTO_CLIENT_ID", "GUSTO_CLIENT_SECRET"] as const; }
export function providerConfiguration(provider: ProviderId, origin: string) {
  const runtimeEnv = env as unknown as Record<string, string | undefined>;
  const [idName, secretName] = envNames(provider); const clientId = runtimeEnv[idName] || ""; const clientSecret = runtimeEnv[secretName] || ""; const encryptionKey = runtimeEnv.INTEGRATION_TOKEN_ENCRYPTION_KEY || ""; const callbackUrl = `${origin}/api/integrations/${provider}/callback`; const missing = [!clientId && idName, !clientSecret && secretName, encryptionKey.length < 24 && "INTEGRATION_TOKEN_ENCRYPTION_KEY"].filter(Boolean) as string[];
  const gustoBase = (runtimeEnv.GUSTO_ENV || "demo").toLowerCase() === "production" ? "https://api.gusto.com" : "https://api.gusto-demo.com"; const quickbooksBase = (runtimeEnv.QUICKBOOKS_ENV || "sandbox").toLowerCase() === "production" ? "https://quickbooks.api.intuit.com" : "https://sandbox-quickbooks.api.intuit.com";
  return { provider, name: providerNames[provider], clientId, clientSecret, encryptionKey, callbackUrl, missing, gustoBase, quickbooksBase, configured: missing.length === 0 };
}
export async function requireOwner() { const viewer = await getViewer(); if (viewer.access !== "owner") return null; await ensureDatabase(); return viewer; }
function encode(bytes: Uint8Array) { let binary = ""; for (const byte of bytes) binary += String.fromCharCode(byte); return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, ""); }
function decode(value: string) { const normalized = value.replace(/-/g, "+").replace(/_/g, "/").padEnd(Math.ceil(value.length / 4) * 4, "="); return Uint8Array.from(atob(normalized), (char) => char.charCodeAt(0)); }
async function tokenKey(secret: string) { if (secret.length < 24) throw new Error("Integration token encryption is not configured."); const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(secret)); return crypto.subtle.importKey("raw", digest, { name: "AES-GCM" }, false, ["encrypt", "decrypt"]); }
async function encryptTokens(tokens: TokenSet, secret: string) { const iv = crypto.getRandomValues(new Uint8Array(12)); const encrypted = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, await tokenKey(secret), new TextEncoder().encode(JSON.stringify(tokens))); return `${encode(iv)}.${encode(new Uint8Array(encrypted))}`; }
async function decryptTokens(value: string, secret: string): Promise<TokenSet> { const [iv, data] = value.split("."); if (!iv || !data) throw new Error("Stored integration credentials are invalid."); const decrypted = await crypto.subtle.decrypt({ name: "AES-GCM", iv: decode(iv) }, await tokenKey(secret), decode(data)); return JSON.parse(new TextDecoder().decode(decrypted)) as TokenSet; }
function stateKey(businessId: string, provider: ProviderId) { return `integration_oauth_state:${businessId}:${provider}`; }
function connectionKey(businessId: string, provider: ProviderId) { return `integration_connection:${businessId}:${provider}`; }
export async function createOAuthState(businessId: string, provider: ProviderId) { const state = encode(crypto.getRandomValues(new Uint8Array(32))); await database().prepare("INSERT INTO workspace_settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value").bind(stateKey(businessId, provider), JSON.stringify({ state, expiresAt: Date.now() + 600000 })).run(); return state; }
export async function consumeOAuthState(businessId: string, provider: ProviderId, candidate: string) { const key = stateKey(businessId, provider); const row = await database().prepare("SELECT value FROM workspace_settings WHERE key = ?").bind(key).first<{ value: string }>(); await database().prepare("DELETE FROM workspace_settings WHERE key = ?").bind(key).run(); try { const stored = row?.value ? JSON.parse(row.value) as { state?: string; expiresAt?: number } : null; if (!stored?.state || !stored.expiresAt || stored.expiresAt < Date.now() || stored.state.length !== candidate.length) return false; let different = 0; for (let index = 0; index < candidate.length; index += 1) different |= candidate.charCodeAt(index) ^ stored.state.charCodeAt(index); return different === 0; } catch { return false; } }
export function authorizationUrl(provider: ProviderId, origin: string, state: string) { const config = providerConfiguration(provider, origin); if (!config.configured) throw new Error(`Missing configuration: ${config.missing.join(", ")}`); if (provider === "quickbooks") return `https://appcenter.intuit.com/connect/oauth2?${new URLSearchParams({ client_id: config.clientId, response_type: "code", scope: "com.intuit.quickbooks.accounting", redirect_uri: config.callbackUrl, state })}`; if (provider === "googleCalendar") return `https://accounts.google.com/o/oauth2/v2/auth?${new URLSearchParams({ client_id: config.clientId, response_type: "code", redirect_uri: config.callbackUrl, scope: "https://www.googleapis.com/auth/calendar.events https://www.googleapis.com/auth/calendar.readonly", access_type: "offline", include_granted_scopes: "true", prompt: "consent", state })}`; if (provider === "slack") return `https://slack.com/oauth/v2/authorize?${new URLSearchParams({ client_id: config.clientId, redirect_uri: config.callbackUrl, scope: "chat:write,channels:read,groups:read", state })}`; return `${config.gustoBase}/oauth/authorize?${new URLSearchParams({ client_id: config.clientId, redirect_uri: config.callbackUrl, response_type: "code", state })}`; }
async function tokenResponse(response: Response) { const payload = await response.json().catch(() => null) as Record<string, unknown> | null; if (!response.ok || !payload || payload.error) throw new Error(String(payload?.error_description || payload?.error || "Provider authorization failed.")); return payload; }
export async function exchangeAuthorizationCode(provider: ProviderId, origin: string, code: string, extra: { realmId?: string }) {
  const config = providerConfiguration(provider, origin); let payload: Record<string, unknown>;
  if (provider === "quickbooks") payload = await tokenResponse(await fetch("https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer", { method: "POST", headers: { authorization: `Basic ${btoa(`${config.clientId}:${config.clientSecret}`)}`, "content-type": "application/x-www-form-urlencoded", accept: "application/json" }, body: new URLSearchParams({ grant_type: "authorization_code", code, redirect_uri: config.callbackUrl }) }));
  else if (provider === "googleCalendar") payload = await tokenResponse(await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: config.clientId, client_secret: config.clientSecret, code, grant_type: "authorization_code", redirect_uri: config.callbackUrl }) }));
  else if (provider === "slack") { payload = await tokenResponse(await fetch("https://slack.com/api/oauth.v2.access", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: config.clientId, client_secret: config.clientSecret, code, redirect_uri: config.callbackUrl }) })); if (payload.ok !== true) throw new Error(String(payload.error || "Slack authorization failed.")); }
  else payload = await tokenResponse(await fetch(`${config.gustoBase}/oauth/token`, { method: "POST", headers: { "content-type": "application/json", "X-Gusto-API-Version": "2026-06-15" }, body: JSON.stringify({ client_id: config.clientId, client_secret: config.clientSecret, redirect_uri: config.callbackUrl, code, grant_type: "authorization_code" }) }));
  const accessToken = String(payload.access_token || ""); if (!accessToken) throw new Error("The provider did not return an access token."); const tokens: TokenSet = { accessToken, refreshToken: payload.refresh_token ? String(payload.refresh_token) : undefined, expiresAt: payload.expires_in ? Date.now() + Number(payload.expires_in) * 1000 : undefined }; let accountId = extra.realmId || "connected"; let accountName = config.name;
  if (provider === "slack") { const team = payload.team as { id?: string; name?: string } | undefined; accountId = team?.id || accountId; accountName = team?.name || accountName; }
  try { if (provider === "googleCalendar") { const info = await fetch("https://www.googleapis.com/calendar/v3/calendars/primary", { headers: { authorization: `Bearer ${accessToken}` } }).then((response) => response.json()) as { id?: string; summary?: string }; accountId = info.id || accountId; accountName = info.summary || accountName; } if (provider === "quickbooks" && extra.realmId) { const info = await fetch(`${config.quickbooksBase}/v3/company/${extra.realmId}/companyinfo/${extra.realmId}?minorversion=75`, { headers: { authorization: `Bearer ${accessToken}`, accept: "application/json" } }).then((response) => response.json()) as { CompanyInfo?: { CompanyName?: string } }; accountName = info.CompanyInfo?.CompanyName || accountName; } if (provider === "gusto") { const info = await fetch(`${config.gustoBase}/v1/token_info`, { headers: { authorization: `Bearer ${accessToken}`, "X-Gusto-API-Version": "2026-06-15" } }).then((response) => response.json()) as { resource_uuid?: string; company_uuid?: string; name?: string }; accountId = info.company_uuid || info.resource_uuid || accountId; accountName = info.name || accountName; } } catch {}
  return { tokens, accountId, accountName };
}
export async function saveConnection(businessId: string, provider: ProviderId, origin: string, tokens: TokenSet, accountId: string, accountName: string) { const config = providerConfiguration(provider, origin); const stored: StoredConnection = { provider, encryptedTokens: await encryptTokens(tokens, config.encryptionKey), accountId, accountName, connectedAt: Date.now() }; await database().prepare("INSERT INTO workspace_settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value").bind(connectionKey(businessId, provider), JSON.stringify(stored)).run(); return stored; }
export async function readConnection(businessId: string, provider: ProviderId) { const row = await database().prepare("SELECT value FROM workspace_settings WHERE key = ?").bind(connectionKey(businessId, provider)).first<{ value: string }>(); try { return row?.value ? JSON.parse(row.value) as StoredConnection : null; } catch { return null; } }
async function refreshTokens(provider: ProviderId, origin: string, tokens: TokenSet) { if (!tokens.refreshToken) return tokens; const config = providerConfiguration(provider, origin); let payload: Record<string, unknown>; if (provider === "quickbooks") payload = await tokenResponse(await fetch("https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer", { method: "POST", headers: { authorization: `Basic ${btoa(`${config.clientId}:${config.clientSecret}`)}`, "content-type": "application/x-www-form-urlencoded", accept: "application/json" }, body: new URLSearchParams({ grant_type: "refresh_token", refresh_token: tokens.refreshToken }) })); else if (provider === "googleCalendar") payload = await tokenResponse(await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: config.clientId, client_secret: config.clientSecret, grant_type: "refresh_token", refresh_token: tokens.refreshToken }) })); else if (provider === "gusto") payload = await tokenResponse(await fetch(`${config.gustoBase}/oauth/token`, { method: "POST", headers: { "content-type": "application/json", "X-Gusto-API-Version": "2026-06-15" }, body: JSON.stringify({ client_id: config.clientId, client_secret: config.clientSecret, redirect_uri: config.callbackUrl, grant_type: "refresh_token", refresh_token: tokens.refreshToken }) })); else return tokens; return { accessToken: String(payload.access_token || tokens.accessToken), refreshToken: String(payload.refresh_token || tokens.refreshToken), expiresAt: payload.expires_in ? Date.now() + Number(payload.expires_in) * 1000 : tokens.expiresAt }; }
export async function validConnectionTokens(businessId: string, provider: ProviderId, origin: string) { const stored = await readConnection(businessId, provider); if (!stored) throw new Error(`${providerNames[provider]} is not connected.`); const config = providerConfiguration(provider, origin); let tokens = await decryptTokens(stored.encryptedTokens, config.encryptionKey); if (tokens.expiresAt && tokens.expiresAt < Date.now() + 60000) { tokens = await refreshTokens(provider, origin, tokens); await saveConnection(businessId, provider, origin, tokens, stored.accountId, stored.accountName); } return { stored, tokens, config }; }
export async function testProviderConnection(businessId: string, provider: ProviderId, origin: string) { const { stored, tokens, config } = await validConnectionTokens(businessId, provider, origin); let response: Response; if (provider === "quickbooks") response = await fetch(`${config.quickbooksBase}/v3/company/${stored.accountId}/companyinfo/${stored.accountId}?minorversion=75`, { headers: { authorization: `Bearer ${tokens.accessToken}`, accept: "application/json" } }); else if (provider === "googleCalendar") response = await fetch("https://www.googleapis.com/calendar/v3/calendars/primary", { headers: { authorization: `Bearer ${tokens.accessToken}` } }); else if (provider === "slack") response = await fetch("https://slack.com/api/auth.test", { method: "POST", headers: { authorization: `Bearer ${tokens.accessToken}` } }); else response = await fetch(`${config.gustoBase}/v1/token_info`, { headers: { authorization: `Bearer ${tokens.accessToken}`, "X-Gusto-API-Version": "2026-06-15" } }); const payload = await response.json().catch(() => null) as { ok?: boolean; error?: string } | null; if (!response.ok || payload?.ok === false) throw new Error(payload?.error || `${config.name} could not verify the connection.`); return { accountName: stored.accountName, checkedAt: Date.now() }; }
export async function disconnectProvider(businessId: string, provider: ProviderId, origin: string) { try { const { tokens, config } = await validConnectionTokens(businessId, provider, origin); if (provider === "googleCalendar") await fetch(`https://oauth2.googleapis.com/revoke?token=${encodeURIComponent(tokens.refreshToken || tokens.accessToken)}`, { method: "POST" }); if (provider === "slack") await fetch("https://slack.com/api/auth.revoke", { method: "POST", headers: { authorization: `Bearer ${tokens.accessToken}` } }); if (provider === "quickbooks") await fetch("https://developer.api.intuit.com/v2/oauth2/tokens/revoke", { method: "POST", headers: { authorization: `Basic ${btoa(`${config.clientId}:${config.clientSecret}`)}`, "content-type": "application/json" }, body: JSON.stringify({ token: tokens.refreshToken || tokens.accessToken }) }); } catch {} await database().prepare("DELETE FROM workspace_settings WHERE key = ?").bind(connectionKey(businessId, provider)).run(); }
